root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
exclude_dir = ["assets", "tmp", "vendor", "frontend"]
delay = 1000
stop_on_error = true
log = "air.log"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
